### ISSUE TITLE
JOSS Review - blakeaw

### ISSUE THREAD

**Issue by blakeaw** [aksholokhov/pysr3#11]
Hello, 

This issue is part of the JOSS review at https://github.com/openjournals/joss-reviews/issues/5155. Here are my comments and questions (the sections mostly correspond to items in my checklist):

------

#### General checks: Data sharing and Reproducibility + Functionality: Functionality and Performance

Could you share the dataset (and code too, if applicable) used to generate the timing results reported in the table of Figure 1? Is it included in the files under paper/synthetic_data_4_1?
	
#### State of the field

Are there any other commonly used packages for regularized regression (using different methods)? 

#### Figure 1

  * Figure 1 isn’t referenced in the text. Although its placement follows the text naturally, it may provide additional clarity to go ahead and add a reference in the preceding sentence.
  * The time measurements don’t specify units. I assume they are in seconds, but it might be good to include this detail in the figure or its caption.
  * It might be helpful to define the abbreviations/acronyms such as ALASSO and SCAD in the Figure caption since they are not defined in the text of the paper. 
  * Here, Adaptive LASSO is abbreviated as ALASSO, but in the docs it is A-LASSO. It might be good to make them consistent.  

#### References

Some references include their DOI and render with the DOI link in the pdf version. Just for consistency, I’d suggest including the DOIs for other references where possible.

#### Community guidelines 

I didn’t see any specific guidelines for reporting issues/problems or seeking support in the docs or README. For example, I think you could point folks to the issues page of the GitHub repo and suggest they open a new issue for reporting issues/problems and seeking support.  

Thanks,
Blake

**Comment by aksholokhov** [comment]
Hello, 

First, thank you for a detailed and very actionable review. I hope that my responses below address your questions and concerns.

> Could you share the dataset (and code too, if applicable) used to generate the timing results reported in the table of Figure 1? Is it included in the files under paper/synthetic_data_4_1?

Of course. All datasets, code, and a complete reproducibility guide are available [here](https://github.com/aksholokhov/msr3-paper). The synthetic datasets are also saved in the directory that you mentioned. 

> Are there any other commonly used packages for regularized regression (using different methods)?

There are, thank you for pointing it out. In [the bigger paper](https://arxiv.org/pdf/2205.06925.pdf) we conducted a comparison of the packages (Table 3), but we omitted it here due to the size constraints. I mentioned the alternative packages explicitly and added a reference to that study in lines 44-46.

> Figure 1 isn’t referenced in the text. Although its placement follows the text naturally, it may provide additional clarity to go ahead and add a reference in the preceding sentence.

Thank you for pointing it out. I added the reference to the figure in the preceding sentence, line 61.

> The time measurements don’t specify units. I assume they are in seconds, but it might be good to include this detail in the figure or its caption.

Right, the time is measured in seconds; I added the measurements to the table.

> It might be helpful to define the abbreviations/acronyms such as ALASSO and SCAD in the Figure caption since they are not defined in the text of the paper.

Right. I defined the abbreviations in lines 53-55. 

> Here, Adaptive LASSO is abbreviated as ALASSO, but in the docs it is A-LASSO. It might be good to make them consistent.

Thank you. I ensured that they are consistent now within the paper. 

> Some references include their DOI and render with the DOI link in the pdf version. Just for consistency, I’d suggest including the DOIs for other references where possible.

Fixed! All DOIs should be in place now. 

> I didn’t see any specific guidelines for reporting issues/problems or seeking support in the docs or README. For example, I think you could point folks to the issues page of the GitHub repo and suggest they open a new issue for reporting issues/problems and seeking support.

The community guidelines are [here](https://aksholokhov.github.io/pysr3/community_guidelines.html); I added a note regarding the issues page on GitHub that you suggested.

Thank you again, 

Aleksei 

EDIT: added the link to the updated version of the paper. It's [here](https://github.com/aksholokhov/pysr3/actions/runs/4548862159).

**Comment by blakeaw** [comment]
Thank you for addressing my comments and clarifying my questions. I have a couple of minor follow-up suggestions:

1. Since the updated version of Figure 1 in the software paper is still pretty similar to Figure 1 of your bigger paper it may be good to add a note in the software paper figure caption stating something like that it is adapted from Figure 1 of Sholokhov 2022. 
2. The msr3-paper repo was very helpful for further testing the code and reproducibility. I'd recommend adding a link to it somewhere in the pysr3 README or docs (or maybe in `pysr3/paper/readme.md`), as well as clarifying that it can also be used to recreate results/figures in Figure 1 of the software paper.  

Thanks,
Blake

**Comment by aksholokhov** [comment]
Thank you for your suggestions, I incorporated both of them: 
1. I added a mention just before the figure that it was adapted from Figure 1 of the bigger paper.
2. I added the link to the reproducibility guide on top of `pysr3/paper/readme.md`. 

Thank you again for all your input. 

Aleksei

**Comment by blakeaw** [comment]
Great! You've addressed all my comments, so I'll go ahead and close this issue and ping the editor in the review thread (https://github.com/openjournals/joss-reviews/issues/5155) to let them know.
